fix Phone throttling issue
jazzband/django-two-factor-auth pull request #419
Opened 2021-06-17 13:33 UTC by kochul2000

## Description

1. resolve #418 (models.PhoneDevice throttling(ThrottlingMixin, TWO_FACTOR_PHONE_THROTTLE_FACTOR) is not properly implemented.)
2. throttling test case has been added.
3. delays(time.sleep(x), x=2^n) are added below the test code that causes phone authentication failure and triggering throttling.

## Motivation and Context

While testing phone authentication(brute force test on authentication in several conditions), I noticed that phone authentication throttling was not working.

## How Has This Been Tested?

by `make test` and dev web site.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-06-17 14:26 UTC, moggers87 commented
Good catch! I'll do a quick review later once Travis has finished

2021-06-17 14:54 UTC, kochul2000 commented
`def generate_challenge(self):`
throttling `generate_challenge` seems not working, and I'm looking for a solution to the problem.
----
thank you for comment :)

2021-06-17 16:54 UTC, kochul2000 commented
```
# two_factor.models.PhoneDevice

def verify_token(self, token):
    ...
    else:
        self.throttle_increment(commit=False)
```
I found the problem with the above code. different `commit` timing between `AuthenticationTokenForm` and `DeviceValidationForm` produces below errors

If `commit=True`, throttling works normally when logging in, 
but it does not pass the `test_views_setup.py` test, and an error occurs if an incorrect code is entered when registering a phone number in setup.

If `commit=False`, throttling doesn't works normally when logging in, 
but test and setup error doesn't occur.

next code works and resolve above problems 
but I believe there's better and prettier way to fix it. 
(The code was so complex that I couldn't figure it out)
```
def verify_token(self, token):
    ...
    else:
        is_commit = True if self.id else False
        self.throttle_increment(commit=is_commit)
```

2021-08-30 21:03 UTC, Bouke requested changes

2021-08-30 21:03 UTC, Bouke commented on tests/test_views_phone.py
> +                time.sleep(2)  # 4, 8, 16, ..., 2^n
Introducing sleeps in the tests makes the test suite run slower. I would suggest finding an alternative. For example by using a fake clock that can be forwarded programmatically.

2023-06-16 05:52 UTC, closed without merging