Email 2fa
jazzband/django-two-factor-auth pull request #423
Opened 2021-07-28 04:25 UTC by pickfire

Revive #267

## Description

Make possible two-factor authorization using emails.

## Motivation and Context

Although this way of two-factor authentication is not very reliable, it can be preferable for some users.

## How Has This Been Tested?

Tested in a local project. Not fully tested but I tried it out. Didn't look closely at old PR.

## Screenshots (if appropriate):
```
Content-Type: multipart/alternative;
 boundary="===============1209054917869947523=="
MIME-Version: 1.0
Subject: Authentication token email
From: hello@test.org
To: hello@example.com
Date: Wed, 28 Jul 2021 04:20:20 -0000
Message-ID: <162744602025.73619.15432270616108599468@mi.localdomain>

--===============1209054917869947523==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

Hello,
Your email address has been given for two-factor authorization on the our website.
If you did't do this, just ignore this message.

Authentication token for user hello is 487008.
--===============1209054917869947523==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<p>Hello,</p>
<p>
    
        Your email address has been given for two-factor authorization on the our website.
        If you did't do this, just ignore this message.
    
</p>
<p>Authentication token for user hello is 487008.</p>
--===============1209054917869947523==--

-------------------------------------------------------------------------------
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-28 14:50 UTC, WayneLambert commented
Hi @pickfire,

Thanks for reviving this and continuing the effort from #267. I am in the midst of considering bolting on a custom implementation using email, however would prefer to adjust/extend the use of this package, so if this is merged, it would greatly help.

It looks like a review is required and is the blocker at the moment. Perhaps you could add @Atterratio as the reviewer?

Thanks again!

2021-07-29 00:40 UTC, pickfire commented
> It looks like a review is required and is the blocker at the moment. Perhaps you could add @Atterratio as the reviewer?

I could but I don't think he will review it since he is not active in the original patch as well.

2021-07-29 08:44 UTC, WayneLambert commented
> I cannot since I don't have permission but I don't think he will review it since he is not active in the original patch as well.

Hi @pickfire, thanks for this.

Perhaps @moggers87 could take a look at this since it is a continuation from the previous PRs work (#267) and seems the most likely contributor to know what is required to get this over the line.

2021-07-30 10:56 UTC, moggers87 commented
I have requested a review from @moggers87

2021-08-14 02:41 UTC, daronzwink commented
This is awesome, and exactly what we were looking for! Thank you very much for picking this enhancement back up and running with it. We would love to apply this to our production environment and wanted to see if there is any chance this could be reviewed and merged?

2021-08-16 01:29 UTC, pickfire commented
I am waiting for reviewer, not sure if the maintainers are still active.

2021-08-16 05:46 UTC, moggers87 requested changes
A few changes required, otherwise good :+1:

2021-08-16 05:46 UTC, moggers87 commented on two_factor/models.py
> +    drift_range = ()
`drift_range` should be set to `None` here. That way if someone forgets to set it, they'll get an error.

2021-08-16 05:46 UTC, moggers87 commented on two_factor/models.py
> +        return getattr(settings, 'TWO_FACTOR_PHONE_THROTTLE_FACTOR', 1)
This should not be in the mixin and there should be a `TWO_FACTOR_EMAIL_THROTTLE_FACTOR` setting for `EmailDevice`

2021-08-16 06:18 UTC, claudep commented
I hoped that #331 would be merged before any new capability addition. The more we wait the more it will be difficult to change the module structure.

2021-08-16 10:34 UTC, moggers87 commented
@claudep that's a slightly bigger change, which is why I keep delaying merging it :laughing:

2021-08-16 10:36 UTC, moggers87 commented
Actually nothing can get merged yet anyway because Travis is down and I need to complete #425 to fix that.

2021-11-19 17:38 UTC, J4bbi commented
I am also interested in email support. And I am guessing it's a feature that would be in demand.

Can I ask what is holding this PR up at the moment? Original PR is from 2018.

@moggers87  it looks like @pickfire has applied your requested changes (admit I haven't looked at the code)

Do you have time for this?

As things stand we might try to implement the PR directly ourselves but we would be more relaxed about it if this PR was merged :) 

Thanks to everyone for their work on this.

2021-12-16 12:44 UTC, giovannicimolin commented
@moggers87 (CC @pickfire) I'm also interested in having this merged. 
Is there anything I can do to help speed up this process? 
Are there any blockers on this?

2022-03-04 16:54 UTC, claudep commented
FYI I'm currently trying to refresh this patch based on the new plugin-based method.

2022-03-04 18:02 UTC, claudep commented
The new version is now in #475.

2022-03-04 18:02 UTC, closed without merging