When validating TOTP in TOTPDeviceForm, allow a drift in clocks of +/-1 instead of just -1
jazzband/django-two-factor-auth pull request #458
Opened 2022-01-03 15:27 UTC by mbakereth

## Description

When validating a TOTP, the TOTPDeviceForm class allows for a clock drift defined by the instance variable tolerance, hardcoded to 1.  While looping of values within this tolerance, the loop started at -tolerance but ended at tolerance-1 instead of tolerance.

A test class is also added.  It sets the time in the TOTP class to a constant value (to make tests deterministic), and confirms the TOTP is accepted when there is an offset of -1, 0 or 1 between the clocks and that it is not accepted when the offset is -2 or +2.

## Motivation and Context
I found when registering and authenticator for the first time, I could only very rarely get the initial TOTP to validate until I made this change.

The change makes the loop the same as in [this example](https://python.hotexamples.com/examples/django_otp.oath/TOTP/drift/python-totp-drift-method-examples.html).

Closes #455 

## How Has This Been Tested?
New test class added as described above.  This confirms it works for the offset values it should work for, and not for one value either side.
All existing tests continue to succeed.  Tested with Python 3.9 on Mac.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-01-03 17:16 UTC, claudep commented
Thanks! Cuuld you please fix the isort/flake8 errors (see pre-commit.ci details).

2022-01-03 19:35 UTC, claudep requested changes
Globally good, thanks! Some minor testing things that could be improved in my opinion.

2022-01-03 19:35 UTC, claudep commented on tests/test_totpdeviceform.py
> +        # prevent it from calling time(), which would make the unittest unpredictable
Instead of monkey-patching, I think it would be a bit more elegant to use mock for this. You should be able to mock `django_otp.oath.time` to return your test value. To be explored...

2022-01-03 19:35 UTC, claudep commented on tests/test_totpdeviceform.py
> +# range, it should be rejected.
I would rather define this part as the docstring of the `TOTPDeviceFormTest`  class.

2022-01-03 19:35 UTC, claudep commented on tests/test_totpdeviceform.py
> +class TOTPDeviceFormTest(UserMixin, TestCase):
I'm not sure that `UserMixin` is required here, did you test removing it?

2022-01-03 19:35 UTC, claudep commented on tests/test_totpdeviceform.py
> +        self.assertFalse(self.form.is_valid())
A little bonus would be to test the form error message (same below).

2022-01-03 19:36 UTC, claudep commented
Could you please also add a line in the CHANGELOG?

2022-01-04 07:34 UTC, mbakereth commented
All added:
- Docstring instead of comment
- @patch (class level) instead of constructor override
- UserMixin dependency removed
- Test error message
- CHANGELOG updated

2022-01-04 07:48 UTC, claudep reviewed
We're almost there! You may squash your commits after the last required change.

2022-01-04 07:48 UTC, claudep commented on tests/test_totpdeviceform.py
> +        django_otp.oath.TOTP.__init__ = self.old_TOTP_init
This method is no longer used.

2022-01-04 09:04 UTC, claudep approved these changes
Thank you again!

2022-01-04 13:16 UTC, merged