Add a registry-based system for plugins
jazzband/django-two-factor-auth pull request #470
Opened 2022-01-29 21:11 UTC by claudep

This is a follow-up to the 07dac39d3, where we try to delegate much of the code specific to particular plugins to the plugins code. There might be some more efforts to do to achieve this final goal, but I think this is already a good step forward.

2022-01-29 21:18 UTC, claudep commented
@moggers87 I would love to get your input on this. I'll gladly fix the code coverage part if the general idea is approved.

2022-01-29 23:02 UTC, moggers87 reviewed
This looks really promising :+1:

2022-02-09 19:04 UTC, moggers87 commented
I have requested a review from @moggers87

2022-02-09 19:18 UTC, claudep commented
Oh, that's a good friend of yours? :-)

2022-03-03 14:35 UTC, claudep commented
@moggers87 I can totally understand that you can't find the time to review this, or more generally to make this package evolve.
Just tell me, and I'll try to find other reviewers.

2022-03-04 01:25 UTC, moggers87 approved these changes
One question, but but approved either way.

This is a great improvement and certainly makes the prospect of adding new methods less daunting (from a maintenance point of view at least)

2022-03-04 01:25 UTC, moggers87 commented on two_factor/plugins/phonenumber/__init__.py
> +if django.VERSION <= (3, 2):
Is this line (and the one for yubikey) necessary? I.e. will Django 4.0 start spitting out warnings if we don't put in this if statement

2022-03-04 01:31 UTC, moggers87 commented
> @moggers87 I can totally understand that you can't find the time to review this, or more generally to make this package evolve. Just tell me, and I'll try to find other reviewers.

Sorry about the wait, I wanted to find the time/energy to give this a proper review. This is some good work :smile_cat:

2022-03-04 01:43 UTC, moggers87 requested changes
Ha! Spoke too soon: `two_factor.plugins.yubikey.utils` has zero test coverage and I think you just forgot to remove that file.

2022-03-04 08:01 UTC, claudep commented on two_factor/plugins/phonenumber/__init__.py
> +if django.VERSION <= (3, 2):
Yes, it is. See 1b6b6a3f9 for the equivalent commit for the main `two_factor` app.
See https://github.com/django/django/blob/stable/4.0.x/django/apps/config.py#L171 for the location where Django raises the warning.

2022-03-04 08:15 UTC, claudep commented
Ah yes, good catch! I removed that file now.

2022-03-04 10:46 UTC, moggers87 approved these changes

2022-03-04 10:47 UTC, merged