Email 2fa through django_otp email plugin
jazzband/django-two-factor-auth pull request #478
Opened 2022-03-05 15:26 UTC by claudep

This is a follow-up pull request after #475, but based on the `EmailDevice` class from `django_otp`.

It also includes the commits from #476 and #477 (may be rebased when those are committed).

2022-03-05 16:35 UTC, claudep commented on two_factor/plugins/email/forms.py
> +                                   'autocomplete': 'one-time-code'})
We might remove those field overrides if #479 is merged, to be tested.

2022-03-22 01:45 UTC, dchukhin commented
Thanks for this work @claudep!
I’m not a maintainer of this library, but I tried your code out locally, and it was very easy to set up 2FA by email ✔️ .
 I did notice an issue for the following scenario, so [I made a pull request against your fork](https://github.com/claudep/django-two-factor-auth/pull/2) to fix it:
1. User without 2FA logs in
2. User sets up 2FA by email
3. User logs out
4. User goes to log back in, enters username and password
5. User is not required to enter 2FA code

2022-04-04 02:52 UTC, moggers87 commented on two_factor/plugins/email/forms.py
> +                                   'autocomplete': 'one-time-code'})
#479 has been merged

2022-04-23 09:59 UTC, claudep commented
@moggers87 I think this is now ready for review.

2022-05-03 19:42 UTC, moggers87 requested changes

2022-05-03 19:42 UTC, moggers87 commented on two_factor/apps.py
> +            registry.register(EmailMethod())
Just to be clear: this one is a comment and not something I'm requesting be changed.

2022-05-07 12:29 UTC, claudep commented on two_factor/apps.py
> +            registry.register(EmailMethod())
You are absolutely right, we should follow the same logic as for other plugins. Thanks for catching!

2022-05-07 12:35 UTC, claudep commented
I still have 2-3 things to fix, hopefully for tomorrow.

2022-05-08 09:13 UTC, claudep commented on tests/test_email.py
> +            self.fail(response.context['form'].errors)
I removed those lines, they are not absolutely needed.

2022-05-08 09:14 UTC, claudep commented on two_factor/apps.py
> +            registry.register(EmailMethod())
Updated to follow the other plugins logic.

2022-05-15 16:02 UTC, moggers87 approved these changes
LGTM, feel free to merge if there were no other changes :+1:

2022-05-15 20:45 UTC, merged