OTP tokens are digits, not integers
jazzband/django-two-factor-auth pull request #479
Opened 2022-03-05 16:31 UTC by claudep

Co-authored-by: "Laurent Mignon (ACSONE)" <laurent.mignon@acsone.eu>

2022-03-20 18:28 UTC, moggers87 requested changes
Just a minor nitpick and one question.

- Will this break if for some reason a user has written their own form HTML and has hard coded the token field to be a numeric input? If that is the case, we might want to highlight that in the changelog when we next do a release.

2022-03-20 18:28 UTC, moggers87 commented on tests/utils.py
> +    return str(totp(key)).zfill(6)
Minor nitpick: we should call `totp_digits()`, otherwise we'll get unnecessary test failures if `TWO_FACTOR_TOTP_DIGITS` ever changes.

2022-03-26 14:27 UTC, claudep commented on tests/utils.py
> +    return str(totp(key)).zfill(6)
Good catch, fixed.

2022-03-26 14:31 UTC, claudep commented
No, nothing in this patch would make a form with `IntegerField` fail. It's just that using an `IntegerField` is risky as possibly the form would clean the token value and strip any initial `0`. In my opinion, a token is never an integer, it's a string composed of digits.

2022-04-04 02:43 UTC, moggers87 approved these changes
Approved

2022-04-04 02:51 UTC, moggers87 commented
As far as I can tell, Codecov is failing because it believes `totp_str` is not covered by tests, despite there being tests that call `totp_str` :upside_down_face: I'm going to merge anyway.

2022-04-04 02:51 UTC, merged