fix submitting Back button on pressing Enter
jazzband/django-two-factor-auth pull request #480
Opened 2022-03-09 16:19 UTC by PetrDlouhy

## Description
If I press Enter on the two factor form, the Back button gets pressed. This fixes that.

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
![Snímek obrazovky_2022-03-09_17-18-33](https://user-images.githubusercontent.com/156755/157483689-b22648e6-0677-4e7b-9a9c-bdac4095c963.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-09 20:50 UTC, claudep requested changes

2022-03-09 20:50 UTC, claudep commented on two_factor/templates/two_factor/_wizard_actions.html
> +  <button name="wizard_goto_step" type="button"
If you do that, clicking the button won't going back, unless you add a JS handler that do something when the button is clicked.

2022-05-05 20:10 UTC, dopry commented on two_factor/templates/two_factor/_wizard_actions.html
> +  <button name="wizard_goto_step" type="button"
@PetrDlouhy do you have time or capacity to address @claudep's change request?

2022-05-06 08:41 UTC, PetrDlouhy commented on two_factor/templates/two_factor/_wizard_actions.html
> +  <button name="wizard_goto_step" type="button"
OK, @claudep is actually right. And it seems, that the first button is always default in HTML: https://stackoverflow.com/questions/1963245/multiple-submit-buttons-on-html-form-designate-one-button-as-default

So if we don't want to colide with user defined form styling, I am duplicating the submit button as hidden to the first place in the form.

2022-09-26 11:53 UTC, PetrDlouhy commented
This seems to be working already with the current master. I am closing this PR.

2022-09-26 11:53 UTC, closed without merging