fix pressing "Use Backup Tokens" if invalid token is already entered
jazzband/django-two-factor-auth pull request #546
Opened 2022-09-26 16:48 UTC by PetrDlouhy

Fix #545,
I added blank block `form_extra_params` to both forms to allow easy setting of i.e. additional classes in overridden form.

## Description

## Motivation and Context
Described in #545 

## How Has This Been Tested?
I have tested this manually since this could be tested only by Selenium or similar tests.

## Screenshots (if appropriate):
![Snímek obrazovky_2022-09-26_18-41-17](https://user-images.githubusercontent.com/156755/192334623-6db593d0-205e-4d79-ae2e-593d8bd79766.png)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-26 18:17 UTC, claudep commented
Thanks for the PR. The `form_extra_params` part is not directly related to this issue, so please remove it from this PR and explain your need and use case in another ticket.

2022-09-27 07:22 UTC, PetrDlouhy commented
@claudep OK, fixed.

2022-09-27 09:08 UTC, claudep requested changes

2022-09-27 09:08 UTC, claudep commented on two_factor/templates/two_factor/core/login.html
> +       <hr/>
nitpick, but I don't think we need the xhtml syntax nowadays, I would simply write it `<hr>`.

2022-09-27 09:08 UTC, claudep commented on two_factor/templates/two_factor/core/login.html
> +       <small>
I'm not convinced about the `small` usage. I'd rather include the section in a `<div>` with a class name so site authors can easily style it through their CSS.

2022-09-27 09:41 UTC, PetrDlouhy commented on two_factor/templates/two_factor/core/login.html
> +       <hr/>
OK

2022-09-27 09:41 UTC, PetrDlouhy commented on two_factor/templates/two_factor/core/login.html
> +       <small>
OK.

2022-09-27 09:43 UTC, claudep approved these changes

2022-09-27 09:44 UTC, claudep commented
Thanks I'll let the PR open some days to let others some time to comment.

2022-10-29 10:08 UTC, merged