issue #145 fix to use any static backup device instead of strictly named
jazzband/django-two-factor-auth pull request #560
Opened 2022-10-14 10:17 UTC by nnseva

## Description
Now any static OTP device can be used as a backup OTP device instead of one strictly having the name `'backup'`.

## Motivation and Context
The `django_otp.plugins.otp_static` package has a management command `addstatictoken` to create a special backup static token that could be used for the OTP backup process.

As described in issue #145 the `addstatictoken` creates a static device named differently from the static device default name used in the `two_factor` package, if no other backup devices are present for the user yet. Because of that, no backup button is shown while login in when the backup code has been created by the `addstatictoken` management command.

## How Has This Been Tested?
Two unit tests have been created altering backup static OTP device names in existing ones.

You can check working the patch yourself. Create your own project using the package, and look at the login process. An unpatched package doesn't show the backup button if the backup code has been created by the `addstatictoken` management command, while the patched one does.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2025-02-19 08:46 UTC, moggers87 requested changes
One minor change required, otherwise looks good :+1:

2025-02-19 08:46 UTC, moggers87 commented on two_factor/views/core.py
> -        return self.request.user.staticdevice_set.get_or_create(name='backup')[0]
`get_or_create` accepts a defaults parameter: https://docs.djangoproject.com/en/5.1/ref/models/querysets/#django.db.models.query.QuerySet.get_or_create

2025-02-24 12:37 UTC, nnseva commented
@moggers87 done

2025-02-24 17:27 UTC, moggers87 approved these changes
LGTM :+1:

2025-02-24 17:27 UTC, merged