Add DEFAULT_AUTO_FIELD in exmple setting
jazzband/django-two-factor-auth pull request #608
Opened 2023-02-26 13:10 UTC by peymanslh

Add DEFAULT_AUTO_FIELD in the examples setting.
It shows a warning when running the example app.

2023-02-26 13:34 UTC, claudep commented
I'd suggest https://github.com/jazzband/django-two-factor-auth/issues/436#issuecomment-1445363150 instead.

2023-02-26 21:29 UTC, claudep requested changes
Thanks! However I think we should only add it to apps that have models.

2023-02-26 21:30 UTC, claudep commented
You may also include a note in the Changelog (in a new Unreleased section).

2023-02-27 09:02 UTC, claudep commented on two_factor/apps.py
> +    default_auto_field = "django.db.models.AutoField"
Is this needed? I think the `two_factor` app has no longer models.

2023-02-27 09:02 UTC, claudep commented on CHANGELOG.md
> +- Add `default_auto_field` in apps config.
I would try to explain the change in more details (defaulting to AutoField...)

2023-02-27 09:14 UTC, peymanslh commented on two_factor/apps.py
> +    default_auto_field = "django.db.models.AutoField"
I saw that there are no models in the `two_factor` app but there was a migration directory in it and it was confusing for me.

2023-02-27 09:22 UTC, peymanslh commented on CHANGELOG.md
> +- Add `default_auto_field` in apps config.
Fixed it.

2023-02-27 09:23 UTC, peymanslh commented on two_factor/apps.py
> +    default_auto_field = "django.db.models.AutoField"
Fixed it.

2023-02-28 08:50 UTC, claudep commented on CHANGELOG.md
> +- Set `default_auto_field` to `AutoField` in apps config that have models for Django>=3.2.
I would write: `Set default_auto_field to AutoField in apps config that have models, so no migrations are generated for projects defaulting to BigAutoField`. What do you think?

2023-02-28 08:51 UTC, claudep commented on CHANGELOG.md
> +- Set `default_auto_field` to `AutoField` in apps config that have models for Django>=3.2.
Oh and I would also mention the ticket number at the end of the note `(#436)`

2023-02-28 12:33 UTC, peymanslh commented
@claudep 
Thanks for your review and suggestion

2023-02-28 13:22 UTC, claudep approved these changes
Thanks!

2023-02-28 13:22 UTC, merged