drop unneeded unique on public_key (#594)
jazzband/django-two-factor-auth pull request #610
Opened 2023-03-02 16:49 UTC by jpaniagualaconich

## Description

Drops the unique constraint on `Webauthn.public_key`.

Modifies two_factor_webauthn migration 0001 so public_key doesn't start with a unique constraint, otherwise it'll fail if the db is MariaDB.

Adds 0002 to drop the unique constraint. It'll still run fine even if there is no unique constraint to drop, resulting in a no-op in that case.

## Motivation and Context

Fixes #594 .
## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-03-02 18:18 UTC, claudep commented on two_factor/plugins/webauthn/migrations/0002_alter_webauthndevice_public_key.py
> +    ]
As Django computes the SQL operations to do by comparing the migrations (and not with the real state of the database), this second migration will be a noop (as `python manage.py sqlmigrate two_factor_webauthn 0002` will tell you) and therefore is not useful (and the unique constraint will stay for existing installations).

2023-03-02 19:17 UTC, jpaniagualaconich commented on two_factor/plugins/webauthn/migrations/0002_alter_webauthndevice_public_key.py
> +    ]
ah, lol, I see. I was completely fooled by it. Indeed, I thought the no-op came from comparing the migration to DB state.

Ugh, will try something different that leaves everything undisturbed unless it's exactly the case described in #594 and get back to you.

2023-04-07 09:49 UTC, jpaniagualaconich commented
OK, ready for another round.

Admittedly a not-super-elegant solution but I like its simplicity.

2023-04-07 12:19 UTC, claudep requested changes
Thanks for trying again, but adding a new setting just for that issue is not an option in my opinion. I would try to subclass `CreateModel` in the initial migration, and alter the model fields in one of its method, `state_forwards` or `database_forwards`, depending on the database connection vendor.

2023-04-08 15:43 UTC, jpaniagualaconich commented
Been there, tried that. Tinkering with `CreateModel`, `state_forwards` and `database_forwards` means too much wading through the entrails of the migration infrastructure.

Also, I didn't want to depend on an undocumented `vendor` attribute.

Anyway, let me propose a somewhat different solution that leaves `CreateModel` and `AlterField` alone and instead modifies `Migration.apply` and `unapply` directly and is perhaps less hacky, at least in my opinion.

2023-04-08 15:58 UTC, claudep reviewed
I like that! Now maybe a dumb question, if we solved the initial migration with index creation on MySQL, can we simply keep that and avoid the second migration?

2023-04-08 16:51 UTC, claudep commented
#616 should solve the test failures.

2023-04-08 18:33 UTC, jpaniagualaconich commented
I'm afraid I don't fully understand your question. Avoid the second migration in which sense?

Applying 0002 for MySQL results in a no-op, so for practical purposes we are avoiding the second migration already.

2023-04-08 18:57 UTC, claudep commented
My (maybe stupid) question was that if we fixed the MySQL issue, can we keep the unique index?

2023-04-10 09:16 UTC, jpaniagualaconich commented
We want model state to be the same in all cases, MySQL or not, after 0002 is applied so a future 0003 migration won't need to do acrobatics like 0001 and 0002 are forced to do now.

When the executor builds the state of the model it uses `Migration.mutate_state` which doesn't get `schema_editor`, meaning that what we can't change things for MySQL since we don't know the database.

As a result, the non-MySQL versions of 0001 and 0002 are used. The consequence of this is that the state of `WebauthnDevice` is wrong for MySQL after `mutate_state` for 0001, getting fixed only after `mutate_state` for 0002.

In any case, having that pesky `unique=True` was totally unneeded in the first place.

2023-04-10 16:44 UTC, claudep commented
That makes a lot of sense. Can you please rebase your PR now? Tests should hopefully pass.

2023-04-12 14:09 UTC, jpaniagualaconich commented
deprecated codecov gave up the ghost?

2023-04-12 14:44 UTC, claudep commented
Looks so... I will not regret it.

2023-04-14 15:33 UTC, claudep commented
Looks like #619 fix this failure.

2023-04-17 15:46 UTC, claudep commented
Could you please rebase on master ? #619 was merged.

2023-04-18 09:04 UTC, jpaniagualaconich commented
done. Looks ready for the merge.

2023-04-18 19:32 UTC, claudep approved these changes
Thanks for your efforts!

2023-04-18 19:32 UTC, merged