Update django-phonenumber-field to 8.x.x
jazzband/django-two-factor-auth pull request #730
Opened 2024-07-17 09:56 UTC by hansegucker

## Motivation and Context

Fix compatibility with django-phonenumber-field 8.0.0

## How Has This Been Tested?

Automatic test suite ran through

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-07-24 06:43 UTC, claudep requested changes
Thanks, a minor change and we are good to go!

2024-07-24 06:43 UTC, claudep commented on CHANGELOG.md
> +## 1.16.1
I think I'd rather have `Unreleased` instead of a fixed number, as only at release time do we know which version number should be used.

2024-07-24 17:32 UTC, hansegucker commented on CHANGELOG.md
> +## 1.16.1
Done

2024-07-24 17:45 UTC, claudep approved these changes
Thanks!

2024-07-24 17:46 UTC, merged

2024-07-24 18:51 UTC, hansegucker commented
> Thanks!

Also thanks! Can we release this soon?

2024-08-12 06:29 UTC, claudep commented
1.17.0 is out!